export const GEM_WALLET = 'gem-wallet';
export const REQUEST_NETWORK = 'REQUEST_NETWORK';
export const REQUEST_CONNECTION = 'REQUEST_CONNECTION';
export const REQUEST_TRANSACTION = 'REQUEST_TRANSACTION';
export const MSG_REQUEST = 'GEM_WALLET_MSG_REQUEST';
export const MSG_RESPONSE = 'GEM_WALLET_MSG_RESPONSE';
