export const GEM_WALLET = 'gem-wallet';
export const REQUEST_NETWORK = 'REQUEST_NETWORK';
export const REQUEST_CONNECTION = 'REQUEST_CONNECTION';
export const RECEIVE_PAYMENT_HASH = 'RECEIVE_PAYMENT_HASH';
export const SEND_PAYMENT = 'SEND_PAYMENT';
export const MSG_REQUEST = 'GEM_WALLET_MSG_REQUEST';
export const MSG_RESPONSE = 'GEM_WALLET_MSG_RESPONSE';
