export const HEADER_HEIGHT_WITHOUT_PADDING = 95;
export const HEADER_VERTICAL_PADDING = 8 + 16;
export const HEADER_HEIGHT = HEADER_HEIGHT_WITHOUT_PADDING + HEADER_VERTICAL_PADDING;
export const NAV_MENU_HEIGHT = 56;
