name: Integration

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Build the extension
        run: yarn build
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: packages/extension/build
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Build the CDN API
        run: yarn build:api:cdn
      - name: Build the npm API
        run: yarn build:api:npm

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test

  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Create cypress.env.json
        run: |
          echo '{' > packages/extension/cypress.env.json
          echo '  "defaultWalletAddress": "'$CYPRESS_defaultWalletAddress'",' >> packages/extension/cypress.env.json
          echo '  "issuerETHAddress": "'$CYPRESS_issuerETHAddress'",' >> packages/extension/cypress.env.json
          echo '  "issuerSOLOAddress": "'$CYPRESS_issuerSOLOAddress'",' >> packages/extension/cypress.env.json
          echo '  "localStorageWallets": "'$CYPRESS_localStorageWallets'",' >> packages/extension/cypress.env.json
          echo '  "mnemonic": "'$CYPRESS_mnemonic'",' >> packages/extension/cypress.env.json
          echo '  "password": "'$CYPRESS_password'",' >> packages/extension/cypress.env.json
          echo '  "seed": "'$CYPRESS_SEED'",' >> packages/extension/cypress.env.json
          echo '}' >> packages/extension/cypress.env.json
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          config-file: cypress.config.ts
          working-directory: packages/extension
