name: Integration

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Build the extension
        run: yarn build
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: packages/extension/build
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Build the CDN API
        run: yarn build:api:cdn
      - name: Build the npm API
        run: yarn build:api:npm

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test

  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          config-file: cypress.config.ts
          working-directory: packages/extension
